repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    namespace: default
    chart: bitnami/postgresql
    values:
      - values-postgresql.yaml
  - name: my-nginx
    namespace: default
    chart: bitnami/nginx
    values:
      - values-nginx.yaml